### ISSUE TITLE
How to retrieve the list of tags?

### ISSUE THREAD

**Issue by yonicsurny** [pikachu987/Tags#2]
Hello, nice library.

I'm just wondering how do you retrieve the list of tags?
The `tagArray` property is private and the `tags` property returns an empty string...

Regards,
Yonic

**Comment by pikachu987** [comment]
Thank you for your good point.

Modified to version 0.1.3
Added tagTextArray and tagArray properties.

Have a nice day :)

2018-02-16 1:21 GMT+09:00 Yonic Surny <notifications@github.com>:
