### ISSUE TITLE
Last Tag problem

### ISSUE THREAD

**Issue by mudassirzulfiqar** [pikachu987/Tags#3]
Last tag problem, the tag always appears with different height.

My code snippet is below

// timeTags is IBOutlets

```
timeTags.tagLayerRadius = 10
timeTags.tags = "123,123,234"

```
![screen shot 2018-07-18 at 2 12 48 pm](https://user-images.githubusercontent.com/22914965/42871842-bee1daee-8a94-11e8-988d-bdb2aab11155.png)

**Comment by pikachu987** [comment]
I do not know why.

![2018-07-18 11 27 12](https://user-images.githubusercontent.com/16880502/42888239-c850d500-8ae2-11e8-8dab-712d6cab5094.png)

![2018-07-18 11 30 54](https://user-images.githubusercontent.com/16880502/42888253-ced0315a-8ae2-11e8-8e23-dee4a2b935c5.png)

You need your exact code to know the cause.
Thank you :)

**Comment by mudassirzulfiqar** [comment]
In your snippet you nil the lastTag, that helped me also, You should mention this in documentation also. Other than that cool library Thanks
